export const incomeCategories: string[] = [
  "Salary",
  "Freelance",
  "Rental",
  "Investment",
  "Business",
  "Pension",
  "Bonuses",
  "Dividends",
  "Grants",
  "Other income",
];

export const expenseCategories: string[] = [
  "Rent/Mortgage",
  "Utilities",
  "Groceries",
  "Transportation",
  "Insurance",
  "Health care",
  "Entertainment",
  "Education",
  "Debt payments",
  "Savings",
  "Subscriptions",
  "Taxes",
  "Clothing",
  "Travel",
  "Other expenses",
];
